name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish-jsr:
    name: Publish packages to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish @open-schema/types
        run: cd types && deno publish

      - name: Publish @open-schema/valibot
        run: cd valibot && deno publish --allow-slow-types

      - name: Publish @open-schema/zod
        run: cd zod && deno publish --allow-slow-types
